language: node_js
node_js: node
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: s3
  bucket: "admin7"
  skip_cleanup: true
  acl: public_read
  region: eu-central-1
  local_dir: build
  detect_encoding: true
  default_text_charset: 'utf-8'
  on:
    repo: "rabotaua/admin7proof"
    branch: master
